[2024-12-15T14:09:43.176-0500] {processor.py:186} INFO - Started process (PID=37241) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:09:43.176-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:09:43.177-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:09:43.177-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:09:43.206-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:09:43.282-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:09:43.282-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:09:43.287-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:09:43.287-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:09:43.293-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.118 seconds
[2024-12-15T14:10:04.335-0500] {processor.py:186} INFO - Started process (PID=37336) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:04.336-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:04.336-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:04.336-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:04.365-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:04.367-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:04.366-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:04.399-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:04.399-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:04.405-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:10:07.296-0500] {processor.py:186} INFO - Started process (PID=37347) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:07.297-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:07.297-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:07.297-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:07.327-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:07.329-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:07.329-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:07.360-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:07.360-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:07.366-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:10:09.040-0500] {processor.py:186} INFO - Started process (PID=37358) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:09.041-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:09.041-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:09.041-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:09.071-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:09.073-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:09.072-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:09.105-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:09.105-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:09.111-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:10:12.903-0500] {processor.py:186} INFO - Started process (PID=37380) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:12.903-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:12.904-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:12.903-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:12.932-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:12.934-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:12.934-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:12.966-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:12.966-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:12.972-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.070 seconds
[2024-12-15T14:10:15.689-0500] {processor.py:186} INFO - Started process (PID=37391) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:15.689-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:15.690-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:15.690-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:15.718-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:15.750-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:15.750-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:15.756-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:15.756-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:15.762-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:10:17.430-0500] {processor.py:186} INFO - Started process (PID=37402) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:17.430-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:17.430-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:17.430-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:17.459-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:17.490-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:17.490-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:17.496-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:17.496-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:17.503-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:10:22.488-0500] {processor.py:186} INFO - Started process (PID=37424) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:22.489-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:22.489-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:22.489-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:22.520-0500] {processor.py:925} INFO - DAG(s) 'multiple_dags' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:22.551-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:22.551-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:22.557-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:22.557-0500] {dag.py:4180} INFO - Setting next_dagrun for multiple_dags to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:10:22.563-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.075 seconds
[2024-12-15T14:10:45.908-0500] {processor.py:186} INFO - Started process (PID=37532) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:45.909-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:45.909-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:45.909-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:45.938-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:45.999-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:45.999-0500] {override.py:1911} INFO - Created Permission View: can edit on DAG:executing_python_operator_dag
[2024-12-15T14:10:46.002-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.002-0500] {override.py:1911} INFO - Created Permission View: can read on DAG:executing_python_operator_dag
[2024-12-15T14:10:46.004-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.004-0500] {override.py:1911} INFO - Created Permission View: can delete on DAG:executing_python_operator_dag
[2024-12-15T14:10:46.006-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.006-0500] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:executing_python_operator_dag
[2024-12-15T14:10:46.008-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.008-0500] {override.py:1911} INFO - Created Permission View: can create on DAG Run:executing_python_operator_dag
[2024-12-15T14:10:46.009-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.009-0500] {override.py:1911} INFO - Created Permission View: can read on DAG Run:executing_python_operator_dag
[2024-12-15T14:10:46.011-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.011-0500] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:executing_python_operator_dag
[2024-12-15T14:10:46.011-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.011-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:46.015-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.015-0500] {dag.py:3262} INFO - Creating ORM DAG for executing_python_operator_dag
[2024-12-15T14:10:46.017-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:46.017-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:10:46.022-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.115 seconds
[2024-12-15T14:10:47.765-0500] {processor.py:186} INFO - Started process (PID=37544) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:47.765-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:47.765-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:47.765-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:47.794-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:47.796-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:47.796-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:47.828-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:47.828-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:10:47.835-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:10:54.910-0500] {processor.py:186} INFO - Started process (PID=37573) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:54.910-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:54.911-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:54.911-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:54.940-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:54.942-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:54.942-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:54.974-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:54.974-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:10:54.980-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:10:56.658-0500] {processor.py:186} INFO - Started process (PID=37584) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:56.659-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:10:56.659-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:56.659-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:56.695-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:10:56.697-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:56.697-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:10:56.731-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:10:56.731-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:10:56.737-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.079 seconds
[2024-12-15T14:11:17.668-0500] {processor.py:186} INFO - Started process (PID=37682) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:17.668-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:11:17.668-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:17.668-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:17.698-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:17.760-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:17.760-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:11:17.765-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:17.765-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:11:17.771-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.105 seconds
[2024-12-15T14:11:29.610-0500] {processor.py:186} INFO - Started process (PID=37738) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:29.611-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:11:29.611-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:29.611-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:29.641-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:29.643-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:29.643-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:11:29.675-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:29.675-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:11:29.682-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.072 seconds
[2024-12-15T14:11:41.810-0500] {processor.py:186} INFO - Started process (PID=37788) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:41.810-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:11:41.811-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:41.811-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:41.856-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:11:41.854-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 17, in <module>
    with DAG(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dag.py", line 698, in __init__
    self.timetable = create_timetable(schedule, self.timezone)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dag.py", line 249, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: datetime.datetime(2024, 12, 14, 0, 0, tzinfo=Timezone('UTC')) is not a valid schedule_interval.
[2024-12-15T14:11:41.856-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:11:41.891-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.082 seconds
[2024-12-15T14:12:00.895-0500] {processor.py:186} INFO - Started process (PID=37875) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:00.896-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:00.896-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:00.896-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:00.927-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:00.989-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:00.988-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:12:00.994-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:00.994-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:12:01.001-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.106 seconds
[2024-12-15T14:12:03.484-0500] {processor.py:186} INFO - Started process (PID=37897) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:03.484-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:03.485-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:03.485-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:03.519-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:03.521-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:03.521-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:12:03.554-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:03.554-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:12:03.560-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.077 seconds
[2024-12-15T14:12:20.398-0500] {processor.py:186} INFO - Started process (PID=37970) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:20.398-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:20.399-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:20.399-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:20.428-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:20.428-0500] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-12-15T14:12:20.430-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:20.431-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:20.431-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:12:20.464-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:20.464-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:12:20.471-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:12:26.526-0500] {processor.py:186} INFO - Started process (PID=37996) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:26.526-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:26.527-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:26.526-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:26.557-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:26.557-0500] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-12-15T14:12:26.558-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:26.560-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:26.560-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:12:26.593-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:26.593-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:12:26.599-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.075 seconds
[2024-12-15T14:12:31.561-0500] {processor.py:186} INFO - Started process (PID=38025) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:31.562-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:31.562-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:31.562-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:31.591-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:31.590-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:12:31.591-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:31.625-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:12:38.261-0500] {processor.py:186} INFO - Started process (PID=38057) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:38.261-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:38.261-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:38.261-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:38.290-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:38.290-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:12:38.291-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:38.326-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:12:47.252-0500] {processor.py:186} INFO - Started process (PID=38097) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:47.252-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:47.253-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:47.253-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:47.253-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:47.253-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 29
    )
    ^
SyntaxError: invalid syntax
[2024-12-15T14:12:47.253-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:47.310-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.059 seconds
[2024-12-15T14:12:50.032-0500] {processor.py:186} INFO - Started process (PID=38109) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:50.032-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:12:50.033-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:50.033-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:50.061-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:12:50.061-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:12:50.061-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:12:50.096-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:13:06.243-0500] {processor.py:186} INFO - Started process (PID=38186) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:06.243-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:06.244-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:06.244-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:06.271-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:06.271-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:06.271-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:06.306-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:13:07.978-0500] {processor.py:186} INFO - Started process (PID=38197) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:07.979-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:07.979-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:07.979-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:08.007-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:08.007-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:08.009-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:08.044-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:13:09.714-0500] {processor.py:186} INFO - Started process (PID=38208) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:09.714-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:09.715-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:09.715-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:09.742-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:09.742-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:09.742-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:09.778-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:13:11.965-0500] {processor.py:186} INFO - Started process (PID=38220) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:11.965-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:11.966-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:11.966-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:11.993-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:11.993-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:11.993-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:12.028-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:13:14.761-0500] {processor.py:186} INFO - Started process (PID=38231) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:14.762-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:14.762-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:14.762-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:14.791-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:14.790-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    taskA = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:14.791-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:14.826-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:13:28.828-0500] {processor.py:186} INFO - Started process (PID=38299) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:28.828-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:28.829-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:28.829-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:28.857-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:28.857-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:28.857-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:28.892-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:13:30.582-0500] {processor.py:186} INFO - Started process (PID=38301) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:30.583-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:30.583-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:30.583-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:30.611-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:30.611-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:30.611-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:30.646-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:13:35.003-0500] {processor.py:186} INFO - Started process (PID=38321) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:35.003-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:35.003-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:35.003-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:35.034-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:35.034-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:35.034-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:35.070-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.068 seconds
[2024-12-15T14:13:38.494-0500] {processor.py:186} INFO - Started process (PID=38344) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:38.495-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:13:38.495-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:38.495-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:38.524-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:13:38.523-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:13:38.524-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:13:38.559-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:14:04.754-0500] {processor.py:186} INFO - Started process (PID=38457) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:04.754-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:14:04.754-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:04.754-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:04.782-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:04.782-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:14:04.782-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:04.818-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:14:06.494-0500] {processor.py:186} INFO - Started process (PID=38468) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:06.495-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:14:06.495-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:06.495-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:06.523-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:06.522-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:14:06.523-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:06.558-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:14:37.718-0500] {processor.py:186} INFO - Started process (PID=38611) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:37.719-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:14:37.719-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:37.719-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:37.747-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:37.746-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:14:37.747-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:37.783-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:14:57.315-0500] {processor.py:186} INFO - Started process (PID=38708) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:57.315-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:14:57.316-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:57.316-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:57.343-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:57.343-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:14:57.343-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:57.378-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:14:59.046-0500] {processor.py:186} INFO - Started process (PID=38719) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:59.046-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:14:59.047-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:59.047-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:59.074-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:14:59.074-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:14:59.074-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:14:59.109-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:15:25.319-0500] {processor.py:186} INFO - Started process (PID=38835) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:25.319-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:15:25.320-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:15:25.320-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:25.348-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:15:25.348-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:15:25.348-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:25.384-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:15:56.081-0500] {processor.py:186} INFO - Started process (PID=38969) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:56.081-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:15:56.082-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:15:56.082-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:56.109-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:15:56.108-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:15:56.109-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:15:56.144-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:16:26.900-0500] {processor.py:186} INFO - Started process (PID=39117) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:26.901-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:16:26.901-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:26.901-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:26.928-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:26.928-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 26, in <module>
    task = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:16:26.929-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:26.964-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:16:54.986-0500] {processor.py:186} INFO - Started process (PID=39240) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:54.986-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:16:54.987-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:54.987-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:55.016-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:55.078-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:55.078-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:16:55.084-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:55.084-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:16:55.091-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.106 seconds
[2024-12-15T14:16:55.945-0500] {processor.py:186} INFO - Started process (PID=39242) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:55.946-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:16:55.946-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:55.946-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:55.975-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:55.977-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:55.977-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:16:56.009-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:56.009-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:16:56.015-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:16:59.490-0500] {processor.py:186} INFO - Started process (PID=39264) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:59.490-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:16:59.491-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:59.491-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:59.522-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:16:59.524-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:59.524-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:16:59.557-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:16:59.557-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:16:59.571-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.083 seconds
[2024-12-15T14:17:30.767-0500] {processor.py:186} INFO - Started process (PID=39422) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:17:30.769-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:17:30.769-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:17:30.769-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:17:30.805-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:17:30.838-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:17:30.838-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:17:30.844-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:17:30.844-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:17:30.850-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.084 seconds
[2024-12-15T14:18:01.510-0500] {processor.py:186} INFO - Started process (PID=39555) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:01.511-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:18:01.511-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:01.511-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:01.540-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:01.571-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:01.571-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:18:01.577-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:01.577-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:18:01.583-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:18:32.377-0500] {processor.py:186} INFO - Started process (PID=39706) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:32.377-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:18:32.378-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:32.378-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:32.407-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:18:32.439-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:32.439-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:18:32.445-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:18:32.445-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:18:32.450-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:19:03.240-0500] {processor.py:186} INFO - Started process (PID=39850) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:03.240-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:03.241-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:03.241-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:03.270-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operator_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:03.302-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:03.302-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:19:03.308-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:03.308-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operator_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:19:03.314-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.075 seconds
[2024-12-15T14:19:16.067-0500] {processor.py:186} INFO - Started process (PID=39913) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:16.068-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:16.068-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:16.068-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:16.097-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:16.096-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 39, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:19:16.097-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:16.132-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:19:26.117-0500] {processor.py:186} INFO - Started process (PID=39962) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:26.118-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:26.118-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:26.118-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:26.151-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:26.150-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 37, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:19:26.151-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:26.186-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.070 seconds
[2024-12-15T14:19:38.785-0500] {processor.py:186} INFO - Started process (PID=40043) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:38.785-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:38.786-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:38.786-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:38.816-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:38.815-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 37, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:19:38.816-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:38.852-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.068 seconds
[2024-12-15T14:19:49.845-0500] {processor.py:186} INFO - Started process (PID=40105) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:49.846-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:49.846-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:49.846-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:49.879-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:49.878-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 38, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:19:49.879-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:49.917-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.073 seconds
[2024-12-15T14:19:56.879-0500] {processor.py:186} INFO - Started process (PID=40153) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:56.880-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:19:56.881-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:56.881-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:56.913-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:19:56.913-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 39, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:19:56.913-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:19:56.950-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.072 seconds
[2024-12-15T14:20:02.826-0500] {processor.py:186} INFO - Started process (PID=40188) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:02.828-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:20:02.828-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:02.828-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:02.860-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:02.859-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 39, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:20:02.860-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:02.898-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.073 seconds
[2024-12-15T14:20:34.189-0500] {processor.py:186} INFO - Started process (PID=40343) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:34.190-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:20:34.190-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:34.190-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:34.227-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:34.226-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 39, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:20:34.227-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:34.271-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.083 seconds
[2024-12-15T14:20:49.232-0500] {processor.py:186} INFO - Started process (PID=40417) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:49.232-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:20:49.232-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:49.232-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:49.260-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:49.259-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:20:49.260-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:49.295-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:20:50.992-0500] {processor.py:186} INFO - Started process (PID=40421) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:50.992-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:20:50.993-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:50.993-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:51.021-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:20:51.020-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:20:51.021-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:20:51.056-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:21:14.377-0500] {processor.py:186} INFO - Started process (PID=40528) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:14.380-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:14.380-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:14.380-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:14.408-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:14.408-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:14.409-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:14.444-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.068 seconds
[2024-12-15T14:21:21.146-0500] {processor.py:186} INFO - Started process (PID=40566) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:21.146-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:21.147-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:21.147-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:21.175-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:21.175-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:21.175-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:21.210-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:21:28.105-0500] {processor.py:186} INFO - Started process (PID=40595) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:28.106-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:28.106-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:28.106-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:28.135-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:28.135-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:28.136-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:28.177-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.073 seconds
[2024-12-15T14:21:31.963-0500] {processor.py:186} INFO - Started process (PID=40615) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:31.963-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:31.963-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:31.963-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:31.991-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:31.991-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:31.991-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:32.026-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:21:34.769-0500] {processor.py:186} INFO - Started process (PID=40627) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:34.769-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:34.769-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:34.769-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:34.797-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:34.797-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:34.797-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:34.832-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:21:36.499-0500] {processor.py:186} INFO - Started process (PID=40638) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:36.500-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:36.500-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:36.500-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:36.528-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:36.527-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:36.528-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:36.563-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:21:39.485-0500] {processor.py:186} INFO - Started process (PID=40652) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:39.486-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:39.486-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:39.486-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:39.515-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:39.515-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:39.515-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:39.550-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:21:54.659-0500] {processor.py:186} INFO - Started process (PID=40720) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:54.659-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:21:54.660-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:54.660-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:54.688-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:21:54.688-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:21:54.688-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:21:54.723-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:22:10.504-0500] {processor.py:186} INFO - Started process (PID=40799) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:10.504-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:22:10.505-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:10.505-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:10.532-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:10.532-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:22:10.532-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:10.568-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:22:41.428-0500] {processor.py:186} INFO - Started process (PID=40938) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:41.428-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:22:41.429-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:41.428-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:41.459-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:41.458-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:22:41.459-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:41.495-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.069 seconds
[2024-12-15T14:22:43.177-0500] {processor.py:186} INFO - Started process (PID=40950) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:43.177-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:22:43.178-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:43.178-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:43.206-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:22:43.205-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 40, in <module>
    python_callable=sample_fun
NameError: name 'sample_fun' is not defined
[2024-12-15T14:22:43.206-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:22:43.241-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:23:01.633-0500] {processor.py:186} INFO - Started process (PID=41036) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:01.633-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:01.634-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:01.634-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:01.662-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:01.662-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 55, in <module>
    task
NameError: name 'task' is not defined
[2024-12-15T14:23:01.662-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:01.697-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:23:03.397-0500] {processor.py:186} INFO - Started process (PID=41049) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:03.398-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:03.398-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:03.398-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:03.426-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:03.425-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 55, in <module>
    task
NameError: name 'task' is not defined
[2024-12-15T14:23:03.426-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:03.461-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:23:06.680-0500] {processor.py:186} INFO - Started process (PID=41060) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:06.680-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:06.680-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:06.680-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:06.710-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:06.710-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 55, in <module>
    task
NameError: name 'task' is not defined
[2024-12-15T14:23:06.711-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:06.746-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.067 seconds
[2024-12-15T14:23:07.659-0500] {processor.py:186} INFO - Started process (PID=41071) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:07.659-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:07.659-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:07.659-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:07.687-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:07.687-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 55, in <module>
    task
NameError: name 'task' is not defined
[2024-12-15T14:23:07.687-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:07.723-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:23:25.513-0500] {processor.py:186} INFO - Started process (PID=41154) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:25.514-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:25.514-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.514-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:25.543-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:25.621-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.621-0500] {override.py:1911} INFO - Created Permission View: can delete on DAG:executing_python_operators_dag
[2024-12-15T14:23:25.624-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.624-0500] {override.py:1911} INFO - Created Permission View: can edit on DAG:executing_python_operators_dag
[2024-12-15T14:23:25.626-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.626-0500] {override.py:1911} INFO - Created Permission View: can read on DAG:executing_python_operators_dag
[2024-12-15T14:23:25.628-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.628-0500] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:executing_python_operators_dag
[2024-12-15T14:23:25.630-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.630-0500] {override.py:1911} INFO - Created Permission View: can create on DAG Run:executing_python_operators_dag
[2024-12-15T14:23:25.632-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.632-0500] {override.py:1911} INFO - Created Permission View: can read on DAG Run:executing_python_operators_dag
[2024-12-15T14:23:25.633-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.633-0500] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:executing_python_operators_dag
[2024-12-15T14:23:25.633-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.633-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:23:25.637-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.637-0500] {dag.py:3262} INFO - Creating ORM DAG for executing_python_operators_dag
[2024-12-15T14:23:25.640-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:25.640-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:23:25.645-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.133 seconds
[2024-12-15T14:23:35.640-0500] {processor.py:186} INFO - Started process (PID=41201) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:35.640-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:35.640-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:35.640-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:35.670-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:35.672-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:35.672-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:23:35.704-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:35.704-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:23:35.711-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.072 seconds
[2024-12-15T14:23:37.475-0500] {processor.py:186} INFO - Started process (PID=41204) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:37.476-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:37.476-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:37.476-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:37.505-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:37.507-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:37.507-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:23:37.539-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:37.539-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:23:37.545-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:23:41.485-0500] {processor.py:186} INFO - Started process (PID=41224) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:41.486-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:41.486-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:41.486-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:41.515-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:41.517-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:41.517-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:23:41.549-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:41.549-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:23:41.556-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:23:56.483-0500] {processor.py:186} INFO - Started process (PID=41293) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:56.483-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:23:56.483-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:56.483-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:56.513-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:23:56.576-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:56.576-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:23:56.582-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:23:56.582-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:23:56.589-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.108 seconds
[2024-12-15T14:24:21.810-0500] {processor.py:186} INFO - Started process (PID=41408) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:21.811-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:24:21.811-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:21.811-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:21.841-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:21.843-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:21.843-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:24:21.876-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:21.876-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:24:21.882-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.073 seconds
[2024-12-15T14:24:23.620-0500] {processor.py:186} INFO - Started process (PID=41419) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:23.621-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:24:23.621-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:23.621-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:23.655-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:23.657-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:23.657-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:24:23.690-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:23.690-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:24:23.696-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.077 seconds
[2024-12-15T14:24:52.031-0500] {processor.py:186} INFO - Started process (PID=41544) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:52.032-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:24:52.032-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:52.032-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:52.061-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:52.125-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:52.124-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:24:52.130-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:52.130-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:24:52.137-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.108 seconds
[2024-12-15T14:24:53.123-0500] {processor.py:186} INFO - Started process (PID=41555) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:53.123-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:24:53.124-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:53.124-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:53.153-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:53.155-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:53.155-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:24:53.188-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:53.188-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:24:53.194-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.072 seconds
[2024-12-15T14:24:54.888-0500] {processor.py:186} INFO - Started process (PID=41566) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:54.888-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:24:54.889-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:54.888-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:54.918-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:24:54.919-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:54.919-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:24:54.952-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:24:54.952-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:24:54.958-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.071 seconds
[2024-12-15T14:25:26.238-0500] {processor.py:186} INFO - Started process (PID=41703) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:26.239-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:25:26.239-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:26.239-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:26.269-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:26.332-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:26.332-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:25:26.338-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:26.338-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:25:26.344-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.107 seconds
[2024-12-15T14:25:31.317-0500] {processor.py:186} INFO - Started process (PID=41732) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:31.317-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:25:31.318-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:31.318-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:31.349-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:31.348-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 42, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:25:31.350-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:31.384-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.069 seconds
[2024-12-15T14:25:33.089-0500] {processor.py:186} INFO - Started process (PID=41743) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:33.089-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:25:33.090-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:33.090-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:33.122-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:33.122-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 42, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:25:33.123-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:33.160-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.072 seconds
[2024-12-15T14:25:33.947-0500] {processor.py:186} INFO - Started process (PID=41745) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:33.947-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:25:33.947-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:33.947-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:33.976-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:25:33.976-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 42, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:25:33.976-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:25:34.012-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.066 seconds
[2024-12-15T14:26:04.758-0500] {processor.py:186} INFO - Started process (PID=41880) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:04.758-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:26:04.758-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:04.758-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:04.786-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:04.785-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 42, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:26:04.786-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:04.821-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.064 seconds
[2024-12-15T14:26:35.615-0500] {processor.py:186} INFO - Started process (PID=42021) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:35.616-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:26:35.616-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:35.616-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:35.643-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:35.643-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 42, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:26:35.643-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:35.679-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:26:37.767-0500] {processor.py:186} INFO - Started process (PID=42033) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:37.768-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:26:37.768-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:37.768-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:37.798-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:26:37.797-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 41, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:26:37.798-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:26:37.834-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.068 seconds
[2024-12-15T14:27:08.787-0500] {processor.py:186} INFO - Started process (PID=42167) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:08.787-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:27:08.787-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:08.787-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:08.815-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:08.814-0500] {dagbag.py:387} ERROR - Failed to import: /Users/apple/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/airflow/dags/python_operator_dag.py", line 41, in <module>
    taskB = PythonOperator(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-12-15T14:27:08.815-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:08.850-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.065 seconds
[2024-12-15T14:27:28.661-0500] {processor.py:186} INFO - Started process (PID=42267) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:28.661-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:27:28.661-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:28.661-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:28.690-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:28.753-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:28.752-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:27:28.758-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:28.758-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:27:28.766-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.106 seconds
[2024-12-15T14:27:59.874-0500] {processor.py:186} INFO - Started process (PID=42403) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:59.875-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:27:59.875-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:59.875-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:59.906-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:27:59.940-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:59.939-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:27:59.945-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:27:59.945-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:27:59.952-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.078 seconds
[2024-12-15T14:28:15.230-0500] {processor.py:186} INFO - Started process (PID=42468) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:15.231-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:28:15.231-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:15.231-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:15.260-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:15.293-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:15.293-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:28:15.299-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:15.299-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-14 00:00:00+00:00, run_after=2024-12-15 00:00:00+00:00
[2024-12-15T14:28:15.305-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.076 seconds
[2024-12-15T14:28:57.301-0500] {processor.py:186} INFO - Started process (PID=42673) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:57.301-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:28:57.302-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:57.302-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:57.330-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:28:57.362-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:57.362-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:28:57.368-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:28:57.368-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:28:57.374-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.074 seconds
[2024-12-15T14:29:28.568-0500] {processor.py:186} INFO - Started process (PID=42823) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:28.568-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:29:28.568-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:28.568-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:28.598-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:28.630-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:28.630-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:29:28.636-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:28.636-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:29:28.642-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.075 seconds
[2024-12-15T14:29:59.635-0500] {processor.py:186} INFO - Started process (PID=42969) to work on /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:59.636-0500] {processor.py:914} INFO - Processing file /Users/apple/airflow/dags/python_operator_dag.py for tasks to queue
[2024-12-15T14:29:59.636-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:59.636-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:59.668-0500] {processor.py:925} INFO - DAG(s) 'executing_python_operators_dag' retrieved from /Users/apple/airflow/dags/python_operator_dag.py
[2024-12-15T14:29:59.701-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:59.701-0500] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-15T14:29:59.706-0500] {logging_mixin.py:190} INFO - [2024-12-15T14:29:59.706-0500] {dag.py:4180} INFO - Setting next_dagrun for executing_python_operators_dag to 2024-12-15 00:00:00+00:00, run_after=2024-12-16 00:00:00+00:00
[2024-12-15T14:29:59.712-0500] {processor.py:208} INFO - Processing /Users/apple/airflow/dags/python_operator_dag.py took 0.078 seconds
