[2024-12-16T14:12:03.022-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T14:12:03.025-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_spark_jar_with_main_class.run_scala_jar_with_class manual__2024-12-16T19:12:00.809428+00:00 [queued]>
[2024-12-16T14:12:03.027-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_spark_jar_with_main_class.run_scala_jar_with_class manual__2024-12-16T19:12:00.809428+00:00 [queued]>
[2024-12-16T14:12:03.027-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-16T14:12:03.031-0500] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): run_scala_jar_with_class> on 2024-12-16 19:12:00.809428+00:00
[2024-12-16T14:12:03.033-0500] {standard_task_runner.py:72} INFO - Started process 99737 to run task
[2024-12-16T14:12:03.036-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'execute_spark_jar_with_main_class', 'run_scala_jar_with_class', 'manual__2024-12-16T19:12:00.809428+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/scala_airflow.py', '--cfg-path', '/var/folders/jw/j912b4gd5xj0c7j8p3syth7r0000gn/T/tmptizl2dw8']
[2024-12-16T14:12:03.038-0500] {standard_task_runner.py:105} INFO - Job 70: Subtask run_scala_jar_with_class
[2024-12-16T14:12:03.053-0500] {task_command.py:467} INFO - Running <TaskInstance: execute_spark_jar_with_main_class.run_scala_jar_with_class manual__2024-12-16T19:12:00.809428+00:00 [running]> on host mac-4254.lan
[2024-12-16T14:12:03.074-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='venkatesh' AIRFLOW_CTX_DAG_ID='execute_spark_jar_with_main_class' AIRFLOW_CTX_TASK_ID='run_scala_jar_with_class' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T19:12:00.809428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T19:12:00.809428+00:00'
[2024-12-16T14:12:03.074-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T14:12:03.084-0500] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-12-16T14:12:03.084-0500] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --name scala_jar_execution_with_class --class org.scala.example.IngestJob --queue root.default /Users/apple/airflow/dags/jar/scalaspark_2.13-0.1.0-SNAPSHOT.jar arg1 arg2
[2024-12-16T14:12:04.336-0500] {spark_submit.py:634} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-12-16T14:12:04.337-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-12-16T14:12:04.338-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-12-16T14:12:04.338-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-12-16T14:12:04.338-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-12-16T14:12:04.338-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-12-16T14:12:04.339-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-12-16T14:12:04.339-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-12-16T14:12:04.339-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-16T14:12:04.339-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-16T14:12:04.339-0500] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-16T14:12:04.357-0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name scala_jar_execution_with_class --class org.scala.example.IngestJob --queue root.default /Users/apple/airflow/dags/jar/scalaspark_2.13-0.1.0-SNAPSHOT.jar arg1 arg2. Error code is: 1.
[2024-12-16T14:12:04.360-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=execute_spark_jar_with_main_class, task_id=run_scala_jar_with_class, run_id=manual__2024-12-16T19:12:00.809428+00:00, execution_date=20241216T191200, start_date=20241216T191203, end_date=20241216T191204
[2024-12-16T14:12:04.364-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T14:12:04.364-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 70 for task run_scala_jar_with_class (Cannot execute: spark-submit --master yarn --name scala_jar_execution_with_class --class org.scala.example.IngestJob --queue root.default /Users/apple/airflow/dags/jar/scalaspark_2.13-0.1.0-SNAPSHOT.jar arg1 arg2. Error code is: 1.; 99737)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name scala_jar_execution_with_class --class org.scala.example.IngestJob --queue root.default /Users/apple/airflow/dags/jar/scalaspark_2.13-0.1.0-SNAPSHOT.jar arg1 arg2. Error code is: 1.
[2024-12-16T14:12:04.397-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-16T14:12:04.402-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-16T14:12:04.402-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
